### ISSUE TITLE
Would like to see stats gathered for the Ceph Object Gateway, iow, object storage metrics processed by the RADOS gateway. Cloud object-based datastores have growing requirements. Thank you.

### ISSUE THREAD

**Issue by wheelerbg** [intelsdi-x/snap-plugin-collector-ceph#27]
**Snap daemon version** (use `snapteld -v`):  1.1.0

**Environment**:
- **Cloud provider or hardware configuration**:  Intel Ivy Bridge CPU
- **OS** (e.g. from /etc/os-release):  RHEL7.2
- **Kernel** (e.g. `uname -a`):  Linux sm136 3.10.0-327.36.1.el7.x86_64 
- **Relevant tools** (e.g. plugins used with Snap):ceph collector, influxdb publisher
- **Others** (e.g. deploying with Ansible):

**What happened**:

**What you expected to happen**:

**Steps to reproduce it** (as minimally and precisely as possible):

1. 
2. 
3. 

**Anything else do we need to know** (e.g. issue happens only occasionally):

**Comment by PatrykMatyjasek** [comment]
Could you try the newest version of plugin? There are some new functionalities, and additional metrics.

**Comment by wheelerbg** [comment]
Hello…  I’m using version 5 of the Ceph Plugin. Looks to be the latest, or ?

I’m looking to get object storage/gateway performance stats similar to rest-bench or COSBench.

Thanks.

Barrie

**Comment by wheelerbg** [comment]
Hello, Patryk…     I’ve been having difficulty getting the Ceph plugin to connect into Grafana. I ran a similar test with the PSUtil plugin and connection to Grafana was fine.

My task starts fine (via the below manifest).
Task watch shows:
[root@sm111 tools-snap]# ./snaptel task watch 348fbb12-9185-4224-8544-bb2098380d48
Watching Task (348fbb12-9185-4224-8544-bb2098380d48):
NAMESPACE        DATA    TIMESTAMP

The Grafana datasource shows successful, and is similar to previous PSUtil test. New DB created for the ceph stats.

Log shows:
tail snap_plugin.log
>>>2017/03/08 14:14:42 Ping received
>>>2017/03/08 14:14:42 CollectMetrics called
>>>2017/03/08 14:14:43 CollectMetrics called
>>>2017/03/08 14:14:44 CollectMetrics called
>>>2017/03/08 14:14:45 CollectMetrics called
>>>2017/03/08 14:14:46 CollectMetrics called
>>>2017/03/08 14:14:47 Ping received
>>>2017/03/08 14:14:47 CollectMetrics called
>>>2017/03/08 14:14:48 CollectMetrics called
>>>2017/03/08 14:14:49 Heartbeat timeout reset

---
  version: 1
  schedule:
    type: "simple"
    interval: "1s"
  max-failures: 1
  workflow:
    collect:
      metrics:
        /intel/storage/ceph/osd/*/osd/op: {}
        /intel/storage/ceph/osd/*/osd/op_cache_hit: {}
        /intel/storage/ceph/osd/*/osd/op_in_bytes: {}
        /intel/storage/ceph/osd/*/osd/op_latency: {}
        /intel/storage/ceph/osd/*/osd/op_out_bytes: {}
        /intel/storage/ceph/osd/*/osd/op_prepare_latency: {}
        /intel/storage/ceph/osd/*/osd/op_process_latency: {}
        /intel/storage/ceph/osd/*/osd/op_r: {}
        /intel/storage/ceph/osd/*/osd/op_r_latency: {}
        /intel/storage/ceph/osd/*/osd/op_r_out_bytes: {}
        /intel/storage/ceph/osd/*/osd/op_r_prepare_latency: {}
        /intel/storage/ceph/osd/*/osd/op_r_process_latency: {}
        /intel/storage/ceph/osd/*/osd/op_rw: {}
        /intel/storage/ceph/osd/*/osd/op_rw_in_bytes: {}
        /intel/storage/ceph/osd/*/osd/op_rw_latency: {}
        /intel/storage/ceph/osd/*/osd/op_rw_out_bytes: {}
        /intel/storage/ceph/osd/*/osd/op_rw_prepare_latency: {}
        /intel/storage/ceph/osd/*/osd/op_rw_process_latency: {}
        /intel/storage/ceph/osd/*/osd/op_rw_rlat: {}
        /intel/storage/ceph/osd/*/osd/op_w: {}
        /intel/storage/ceph/osd/*/osd/op_w_in_bytes: {}
        /intel/storage/ceph/osd/*/osd/op_w_latency: {}
        /intel/storage/ceph/osd/*/osd/op_w_prepare_latency: {}
        /intel/storage/ceph/osd/*/osd/op_w_process_latency: {}
        /intel/storage/ceph/osd/*/osd/op_w_rlat: {}
      publish:
        - plugin_name: "influxdb"
          config:
             host: "apss131"
             #host: "${INFLUXDB_HOST}"
             port: 8086
             database: "ceph-111"
             user: "admin"
             password: "admin"
             scheme: http
             skip-verify: false
             isMultiFields: true

Can you tell me what I may be doing wrong with this task? I am running the task as root on one of my Ceph OSD nodes.

Your assistance greatly appreciated.

Barrie Wheeler

**Comment by wheelerbg** [comment]
Patryk,  I see that v6 of the Ceph Plugin came out earlier today and I’ve loaded that plugin.

The connection into Grafana now works and stats are available. I will continue to work with it and get back with you.

Is this the right means of asking our plugin>Grafana questions?

Thanks.

Barrie
From: Wheeler, Barrie
Sent: Wednesday, March 8, 2017 2:19 PM
To: 'intelsdi-x/snap-plugin-collector-ceph' <reply@reply.github.com>; intelsdi-x/snap-plugin-collector-ceph <snap-plugin-collector-ceph@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [intelsdi-x/snap-plugin-collector-ceph] Would like to see stats gathered for the Ceph Object Gateway, iow, object storage metrics processed by the RADOS gateway. Cloud object-based datastores have growing requirements. Thank you. (#27)

Hello, Patryk…     I’ve been having difficulty getting the Ceph plugin to connect into Grafana. I ran a similar test with the PSUtil plugin and connection to Grafana was fine.

My task starts fine (via the below manifest).
Task watch shows:
[root@sm111 tools-snap]# ./snaptel task watch 348fbb12-9185-4224-8544-bb2098380d48
Watching Task (348fbb12-9185-4224-8544-bb2098380d48):
NAMESPACE        DATA    TIMESTAMP

The Grafana datasource shows successful, and is similar to previous PSUtil test. New DB created for the ceph stats.

Log shows:
tail snap_plugin.log
>>>2017/03/08 14:14:42 Ping received
>>>2017/03/08 14:14:42 CollectMetrics called
>>>2017/03/08 14:14:43 CollectMetrics called
>>>2017/03/08 14:14:44 CollectMetrics called
>>>2017/03/08 14:14:45 CollectMetrics called
>>>2017/03/08 14:14:46 CollectMetrics called
>>>2017/03/08 14:14:47 Ping received
>>>2017/03/08 14:14:47 CollectMetrics called
>>>2017/03/08 14:14:48 CollectMetrics called
>>>2017/03/08 14:14:49 Heartbeat timeout reset

---
  version: 1
  schedule:
    type: "simple"
    interval: "1s"
  max-failures: 1
  workflow:
    collect:
      metrics:
        /intel/storage/ceph/osd/*/osd/op: {}
        /intel/storage/ceph/osd/*/osd/op_cache_hit: {}
        /intel/storage/ceph/osd/*/osd/op_in_bytes: {}
        /intel/storage/ceph/osd/*/osd/op_latency: {}
        /intel/storage/ceph/osd/*/osd/op_out_bytes: {}
        /intel/storage/ceph/osd/*/osd/op_prepare_latency: {}
        /intel/storage/ceph/osd/*/osd/op_process_latency: {}
        /intel/storage/ceph/osd/*/osd/op_r: {}
        /intel/storage/ceph/osd/*/osd/op_r_latency: {}
        /intel/storage/ceph/osd/*/osd/op_r_out_bytes: {}
        /intel/storage/ceph/osd/*/osd/op_r_prepare_latency: {}
        /intel/storage/ceph/osd/*/osd/op_r_process_latency: {}
        /intel/storage/ceph/osd/*/osd/op_rw: {}
        /intel/storage/ceph/osd/*/osd/op_rw_in_bytes: {}
        /intel/storage/ceph/osd/*/osd/op_rw_latency: {}
        /intel/storage/ceph/osd/*/osd/op_rw_out_bytes: {}
        /intel/storage/ceph/osd/*/osd/op_rw_prepare_latency: {}
        /intel/storage/ceph/osd/*/osd/op_rw_process_latency: {}
        /intel/storage/ceph/osd/*/osd/op_rw_rlat: {}
        /intel/storage/ceph/osd/*/osd/op_w: {}
        /intel/storage/ceph/osd/*/osd/op_w_in_bytes: {}
        /intel/storage/ceph/osd/*/osd/op_w_latency: {}
        /intel/storage/ceph/osd/*/osd/op_w_prepare_latency: {}
        /intel/storage/ceph/osd/*/osd/op_w_process_latency: {}
        /intel/storage/ceph/osd/*/osd/op_w_rlat: {}
      publish:
        - plugin_name: "influxdb"
          config:
             host: "apss131"
             #host: "${INFLUXDB_HOST}"
             port: 8086
             database: "ceph-111"
             user: "admin"
             password: "admin"
             scheme: http
             skip-verify: false
             isMultiFields: true

Can you tell me what I may be doing wrong with this task? I am running the task as root on one of my Ceph OSD nodes.

Your assistance greatly appreciated.

Barrie Wheeler

**Comment by PatrykMatyjasek** [comment]
@wheelerbg if there are problems with grafana, you can create an issue on its repo. Please provide there some information like: logs, configuration, task, etc.

**Comment by PatrykMatyjasek** [comment]
@mkleina could you take a look at this?

**Comment by mkleina** [comment]
@wheelerbg Thank you for your question, I am happy that stats are now available for you after update! Ceph collector in the latest version 6 is automatically generating available metrics list based on your Ceph perf schema, so you can access all available metrics regardless of your Ceph setup configuration. If you got recent Ceph version, then you can also access descriptions for most metrics (try to run `snaptel metric list --verbose`), so you can check what every metric means.

You can check daemon socket perf schema contents running ceph binary directly:
`ceph --admin-daemon <DAEMON_SOCKET_FILE.asok> perf schema`

The result will be something like:
```
...
"cluster": {
        "num_mon": {
            "type": 2,
            "description": "Monitors",
            "nick": ""
        },
        "num_mon_quorum": {
            "type": 2,
            "description": "Monitors in quorum",
            "nick": ""
        },
        "num_osd": {
            "type": 2,
            "description": "OSDs",
            "nick": ""
        },
        "num_osd_up": {
            "type": 2,
            "description": "OSDs that are up",
            "nick": ""
        },
...
```

and this is actual data source for this plugin.

**It is possible that Ceph simply does not provide metrics you're asking for, but these metrics looks like derived metrics and can be calculated based on already existing "put" metric for example.**

As you're using InfluxDB as Grafana's data source, all you want is to add `DERIVATIVE()` function to your dashboard query, find more here:
https://docs.influxdata.com/influxdb/v0.9/query_language/functions/#derivative

**Comment by wheelerbg** [comment]
Thank you, Kleina…

That’s very helpful. These derivatives are some of what I’m looking for.

field (get_b)     derivative (1s)     Reads throughput 4K - @3Mil b/s
field (put_b)     derivative (1s)    Writes throughput 4K - @400K b/s

Question on these metrics:
/intel/storage/ceph/client/[client_id]/client.rgw.sm141/get                                                      6                       Gets
/intel/storage/ceph/client/[client_id]/client.rgw.sm141/put                                                      6                       Puts
Do these present the number of get and put operations? So with a derivative of 1s, we have read/write ops per sec?

Also,  does the plugin only capture metrics?  Can you start/run metrics via the plugin, or is an external workload required?

I’ll test a few other options to see if we can come up with some interesting derivative metrics.

Greatly appreciate your help!

Barrie

**Comment by mkleina** [comment]
@wheelerbg 

> Question on these metrics:
> /intel/storage/ceph/client/[client_id]/client.rgw.sm141/get                                                      6                       Gets
> /intel/storage/ceph/client/[client_id]/client.rgw.sm141/put                                                      6                       Puts
> Do these present the number of get and put operations?

Probably yes, I couldn't find info about it, but it looks like that.

> So with a derivative of 1s, we have read/write ops per sec?

Yes.

> Also, does the plugin only capture metrics? 

Yes.

> Can you start/run metrics via the plugin, or is an external workload required?

I don't know what do you mean by starting metrics, but the plugin takes metrics from already running Ceph daemon and you need to start this daemon on your own. If you mean start / stop collecting metrics, it can be done using `snaptel task stop` and `snaptel task start` commands.

I hope it will help :slightly_smiling_face:

**Comment by wheelerbg** [comment]
Thank you for your assistance with this.  Snap and the Ceph plugin with Influxdb and Grafana have been functioning well.

Barrie
